using System;
using System.Collections.Generic;
using System.IO;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Newtonsoft.Json;

namespace HospitalSchedulerUI
{
    public partial class EmergencyTriage : UserControl
    {
        public EmergencyTriage()
        {
            InitializeComponent();
            // Wire up events (XAML does not attach handlers)
            btnCalculate.Click += btnCalculate_Click;
            btnPrintReport.Click += btnPrintReport_Click;
            sliderPain.ValueChanged += SliderPain_ValueChanged;
            // Initialize pain label
            UpdatePainLabel((int)sliderPain.Value);
        }

        private void btnCalculate_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var result = CalculateTriage();

                // Update UI
                txtUrgencyScore.Text = string.Format("{0}/10", result.Score);
                txtPriority.Text = result.Priority;
                txtAction.Text = result.Action;
                txtDepartment.Text = result.Department;
                txtWaitTime.Text = result.WaitTime;
                txtMainSymptom.Text = result.MainSymptom ?? "--";
                txtSymptomsCount.Text = result.SymptomsCount.ToString();
                txtAIScore.Text = string.Format("{0}%", result.AIConfidence);
                txtStatus.Text = "Assessment complete";

                // Color bar
                if (result.Score >= 8)
                    urgencyColorBar.Background = new SolidColorBrush(Colors.Red);
                else if (result.Score >= 5)
                    urgencyColorBar.Background = new SolidColorBrush(Colors.Orange);
                else
                    urgencyColorBar.Background = new SolidColorBrush(Colors.Green);

                // Show quick message
                MessageBox.Show(string.Format("Urgency Level: {0}/10\nPriority: {1}\nAction: {2}", result.Score, result.Priority, result.Action),
                                "Triage Result", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error during triage: " + ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

       
        private void btnPrintReport_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var result = CalculateTriage();

                StringBuilder sb = new StringBuilder();
                sb.AppendLine("EMERGENCY TRIAGE REPORT");
                sb.AppendLine("Generated: " + DateTime.Now.ToString("g"));
                sb.AppendLine();
                sb.AppendLine("Patient Name: " + (txtPatientName.Text ?? "Unknown"));
                sb.AppendLine("Age: " + txtAge.Text);
                sb.AppendLine("Main Symptom: " + (result.MainSymptom ?? "--"));
                sb.AppendLine("Symptoms Count: " + result.SymptomsCount);
                sb.AppendLine("Urgency Score: " + result.Score + "/10");
                sb.AppendLine("Priority: " + result.Priority);
                sb.AppendLine("Recommended Action: " + result.Action);
                sb.AppendLine("Department: " + result.Department);
                sb.AppendLine();
                sb.AppendLine("Notes: This report was generated by the built-in triage calculator.");

                string exeDir = AppDomain.CurrentDomain.BaseDirectory;
                string projectRoot = exeDir;
                for (int i = 0; i < 3; i++)
                {
                    var parent = Directory.GetParent(projectRoot);
                    if (parent != null)
                        projectRoot = parent.FullName;
                }

                string resultsFolder = Path.Combine(projectRoot, "Results");
                Directory.CreateDirectory(resultsFolder);

                // Save plain text backup
                string reportTxtPath = Path.Combine(resultsFolder, "triage_report.txt");
                File.WriteAllText(reportTxtPath, sb.ToString(), Encoding.UTF8);

                // Build a nicer HTML report for display
                string html = $@"<!doctype html>
<html>
<head>
  <meta charset='utf-8'/>
  <title>Triage Report</title>
  <style>
    body {{ font-family: Arial, Helvetica, sans-serif; margin: 30px; color:#333 }}
    .header {{ background:#1a5276; color:white; padding:20px; border-radius:8px }}
    .section {{ margin-top:20px; padding:15px; border:1px solid #ddd; border-radius:6px; background:#fafafa }}
    .label {{ font-weight:bold; width:200px; display:inline-block }}
    .score {{ font-size:48px; color:#1a5276; font-weight:bold }}
  </style>
</head>
<body>
  <div class='header'>
    <h1>Emergency Triage Report</h1>
    <div>Generated: {DateTime.Now.ToString("g")}</div>
  </div>

  <div class='section'>
    <div><span class='label'>Patient Name:</span> {System.Net.WebUtility.HtmlEncode(txtPatientName.Text ?? "Unknown")}</div>
    <div><span class='label'>Age:</span> {System.Net.WebUtility.HtmlEncode(txtAge.Text)}</div>
    <div style='margin-top:10px'><span class='label'>Urgency Score:</span> <span class='score'>{result.Score}/10</span></div>
    <div style='margin-top:6px'><span class='label'>Priority:</span> {System.Net.WebUtility.HtmlEncode(result.Priority)}</div>
    <div><span class='label'>Recommended Action:</span> {System.Net.WebUtility.HtmlEncode(result.Action)}</div>
    <div><span class='label'>Department:</span> {System.Net.WebUtility.HtmlEncode(result.Department)}</div>
    <div><span class='label'>Recommended Specialist:</span> {System.Net.WebUtility.HtmlEncode(result.RecommendedSpecialist)}</div>
    <div><span class='label'>Estimated Wait Time:</span> {System.Net.WebUtility.HtmlEncode(result.WaitTime)}</div>
  </div>

  <div class='section'>
    <h3>Details</h3>
    <div><span class='label'>Main Symptom:</span> {System.Net.WebUtility.HtmlEncode(result.MainSymptom ?? "--")}</div>
    <div><span class='label'>Total Symptoms:</span> {result.SymptomsCount}</div>
    <div><span class='label'>Pain Level:</span> {sliderPain.Value}/10</div>
    <div><span class='label'>AI Confidence:</span> {result.AIConfidence}%</div>
  </div>

  <div class='section'>
    <h3>Notes</h3>
    <p>This report is an automated triage assessment. It is not a substitute for professional medical judgment.</p>
  </div>

</body>
</html>";

                // Save to user's Documents for visibility as well as Results
                var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                string userFolder = Path.Combine(documents, "MediMatch", "TriageReports");
                Directory.CreateDirectory(userFolder);
                string htmlPath = Path.Combine(userFolder, $"triage_report_{DateTime.Now.ToString("yyyyMMdd_HHmmss")}.html");
                File.WriteAllText(htmlPath, html, Encoding.UTF8);

                // Also copy HTML into Results for consistency
                string resultsHtml = Path.Combine(resultsFolder, "triage_report.html");
                File.WriteAllText(resultsHtml, html, Encoding.UTF8);

                // Open HTML in default browser for user to view
                try
                {
                    Process.Start(new ProcessStartInfo(htmlPath) { UseShellExecute = true });
                }
                catch {
                    // fallback: try opening resultsHtml
                    try { Process.Start(new ProcessStartInfo(resultsHtml) { UseShellExecute = true }); } catch { }
                }

                MessageBox.Show("Report saved and opened. A copy is in Results/triage_report.txt and your Documents/MediMatch/TriageReports.", "Report Generated", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Failed to save report: " + ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void SliderPain_ValueChanged(object sender, RoutedPropertyChangedEventArgs<double> e)
        {
            UpdatePainLabel((int)e.NewValue);
        }

        private void UpdatePainLabel(int value)
        {
            string text = value + " - ";
            if (value <= 3) text += "Mild";
            else if (value <= 6) text += "Moderate";
            else text += "Severe";

            lblPainValue.Text = text;
        }

        private int ParseIntOrDefault(string s, int def)
        {
            int v;
            return int.TryParse(s, out v) ? v : def;
        }

        private class TriageResult
        {
            public int Score { get; set; }
            public string Priority { get; set; }
            public string Action { get; set; }
            public string Department { get; set; }
            public string WaitTime { get; set; }
            public string MainSymptom { get; set; }
            public int SymptomsCount { get; set; }
            public int AIConfidence { get; set; }
            public string RecommendedSpecialist { get; set; } 
        }

        private TriageResult CalculateTriage()
        {
            // Improved algorithm:
            // - Use stronger weights for serious symptoms
            // - Apply synergy multiplier when multiple critical signs present
            // - Map raw score to 0-10 using an exponential mapping so larger raw values escalate quickly
            var weights = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase)
            {
                { "chkChestPain", 6.0 },
                { "chkBreathing", 6.0 },
                { "chkBleeding", 7.0 },
                { "chkFever", 1.5 },
                { "chkHeadInjury", 6.5 },
                { "chkBrokenBone", 3.5 },
                { "chkAbdominalPain", 3.0 },
                { "chkDizziness", 1.5 },
                { "chkUnconscious", 9.0 },
                { "chkBurn", 5.0 }
            };

            var selected = new List<string>();
            if (chkChestPain.IsChecked == true) selected.Add("Chest Pain");
            if (chkBreathing.IsChecked == true) selected.Add("Difficulty Breathing");
            if (chkBleeding.IsChecked == true) selected.Add("Severe Bleeding");
            if (chkFever.IsChecked == true) selected.Add("High Fever");
            if (chkHeadInjury.IsChecked == true) selected.Add("Head Injury");
            if (chkBrokenBone.IsChecked == true) selected.Add("Broken Bone");
            if (chkAbdominalPain.IsChecked == true) selected.Add("Abdominal Pain");
            if (chkDizziness.IsChecked == true) selected.Add("Dizziness");
            if (chkUnconscious.IsChecked == true) selected.Add("Unconscious");
            if (chkBurn.IsChecked == true) selected.Add("Severe Burns");

            // Sum weighted score
            double raw = 0.0;
            if (chkChestPain.IsChecked == true) raw += weights["chkChestPain"];
            if (chkBreathing.IsChecked == true) raw += weights["chkBreathing"];
            if (chkBleeding.IsChecked == true) raw += weights["chkBleeding"];
            if (chkFever.IsChecked == true) raw += weights["chkFever"];
            if (chkHeadInjury.IsChecked == true) raw += weights["chkHeadInjury"];
            if (chkBrokenBone.IsChecked == true) raw += weights["chkBrokenBone"];
            if (chkAbdominalPain.IsChecked == true) raw += weights["chkAbdominalPain"];
            if (chkDizziness.IsChecked == true) raw += weights["chkDizziness"];
            if (chkUnconscious.IsChecked == true) raw += weights["chkUnconscious"];
            if (chkBurn.IsChecked == true) raw += weights["chkBurn"];

            // Pain influence
            double painInfluence = (sliderPain.Value - 1) / 9.0 * 3.0; // up to 3 points
            raw += painInfluence;

            // Age influence
            int age = ParseIntOrDefault(txtAge.Text, 30);
            if (age < 5 || age >= 75) raw += 2.0;
            else if (age < 12 || age >= 65) raw += 1.0;

            // Critical symptoms set
            var criticalFlags = new[] { chkUnconscious.IsChecked == true, chkChestPain.IsChecked == true, chkBreathing.IsChecked == true, chkBleeding.IsChecked == true, chkHeadInjury.IsChecked == true, chkBurn.IsChecked == true };
            int criticalCount = criticalFlags.Count(f => f);

            // Apply synergy: multiple critical signs drastically increase urgency
            if (criticalCount >= 2)
            {
                raw *= 1.6 + (criticalCount - 2) * 0.3; // increase multiplier for more critical signs
            }

            // Absolute overrides for catastrophic combinations
            if ((chkBleeding.IsChecked == true && chkUnconscious.IsChecked == true) || (chkBreathing.IsChecked == true && chkUnconscious.IsChecked == true))
            {
                raw = Math.Max(raw, 18.0); // force a very high raw value
            }

            // Map raw to 0-10 using exponential mapping so higher raw values quickly approach 10
            // parameter k controls steepness; lower k => faster escalation
            double k = 4.0; // tuned for the chosen weights
            double scaled = (1.0 - Math.Exp(-raw / k)) * 10.0;
            int score = (int)Math.Round(Math.Min(10.0, Math.Max(0.0, scaled)));

            // Ensure unconscious or severe bleeding alone are high
            if (chkUnconscious.IsChecked == true && score < 8) score = 9;
            if (chkBleeding.IsChecked == true && score < 7 && criticalCount >= 1) score = Math.Max(score, 7);

            // Determine main symptom by highest weight present
            string mainSymptom = null;
            double bestW = -1;
            if (chkUnconscious.IsChecked == true && weights["chkUnconscious"] > bestW) { mainSymptom = "Unconscious/Confused"; bestW = weights["chkUnconscious"]; }
            if (chkBleeding.IsChecked == true && weights["chkBleeding"] > bestW) { mainSymptom = "Severe Bleeding"; bestW = weights["chkBleeding"]; }
            if (chkChestPain.IsChecked == true && weights["chkChestPain"] > bestW) { mainSymptom = "Chest Pain"; bestW = weights["chkChestPain"]; }
            if (chkBreathing.IsChecked == true && weights["chkBreathing"] > bestW) { mainSymptom = "Difficulty Breathing"; bestW = weights["chkBreathing"]; }
            if (chkHeadInjury.IsChecked == true && weights["chkHeadInjury"] > bestW) { mainSymptom = "Head Injury"; bestW = weights["chkHeadInjury"]; }
            if (chkBurn.IsChecked == true && weights["chkBurn"] > bestW) { mainSymptom = "Severe Burns"; bestW = weights["chkBurn"]; }
            if (mainSymptom == null && selected.Count > 0) mainSymptom = selected[0];

            // Priority & action mapping
            string priority;
            string action;
            string department;
            string waitTime;

            if (score >= 9)
            {
                priority = "Critical";
                action = "Immediate resuscitation / Advanced life support";
                department = "Emergency / Resuscitation";
                waitTime = "0-5 minutes";
            }
            else if (score >= 7)
            {
                priority = "High";
                action = "Urgent assessment and intervention";
                department = MapDepartment(mainSymptom);
                waitTime = "5-15 minutes";
            }
            else if (score >= 5)
            {
                priority = "Urgent";
                action = "Rapid assessment and treatment";
                department = MapDepartment(mainSymptom);
                waitTime = "15-45 minutes";
            }
            else
            {
                priority = "Non-Urgent";
                action = "Routine assessment and scheduling";
                department = MapDepartment(mainSymptom);
                waitTime = "60+ minutes";
            }

            int aiConfidence = Math.Min(99, 40 + score * 6);
            string specialist = MapSpecialist(mainSymptom);
            return new TriageResult
            {
                Score = score,
                Priority = priority,
                Action = action,
                Department = department,
                WaitTime = waitTime,
                MainSymptom = mainSymptom,
                SymptomsCount = selected.Count,
                AIConfidence = aiConfidence,
                RecommendedSpecialist = specialist // <--- ADD THIS LINE

            };
        }

        private string MapDepartment(string mainSymptom)
        {
            if (string.IsNullOrEmpty(mainSymptom)) return "General";
            if (mainSymptom.IndexOf("Chest", StringComparison.OrdinalIgnoreCase) >= 0) return "Cardiology";
            if (mainSymptom.IndexOf("Breath", StringComparison.OrdinalIgnoreCase) >= 0) return "Pulmonology / Emergency";
            if (mainSymptom.IndexOf("Bleed", StringComparison.OrdinalIgnoreCase) >= 0) return "Emergency / Trauma";
            if (mainSymptom.IndexOf("Head", StringComparison.OrdinalIgnoreCase) >= 0) return "Neurology / Trauma";
            if (mainSymptom.IndexOf("Broken", StringComparison.OrdinalIgnoreCase) >= 0) return "Orthopedics";
            if (mainSymptom.IndexOf("Fever", StringComparison.OrdinalIgnoreCase) >= 0) return "Internal Medicine";
            if (mainSymptom.IndexOf("Abdominal", StringComparison.OrdinalIgnoreCase) >= 0) return "General Surgery";
            if (mainSymptom.IndexOf("Burn", StringComparison.OrdinalIgnoreCase) >= 0) return "Burns Unit";
            if (mainSymptom.IndexOf("Dizziness", StringComparison.OrdinalIgnoreCase) >= 0) return "Neurology";
            if (mainSymptom.IndexOf("Unconscious", StringComparison.OrdinalIgnoreCase) >= 0) return "Emergency";
            return "General";
        }
        private string MapSpecialist(string mainSymptom)
        {
            if (string.IsNullOrEmpty(mainSymptom)) return "General Practitioner";

            if (mainSymptom.Contains("Chest Pain")) return "Cardiologist (Heart Specialist)";
            if (mainSymptom.Contains("Breathing")) return "Pulmonologist (Lung Specialist)";
            if (mainSymptom.Contains("Bleeding")) return "Trauma Surgeon";
            if (mainSymptom.Contains("Head Injury")) return "Neurologist";
            if (mainSymptom.Contains("Unconscious")) return "Neurologist / Critical Care";
            if (mainSymptom.Contains("Broken Bone")) return "Orthopedic Surgeon";
            if (mainSymptom.Contains("Abdominal")) return "Gastroenterologist";
            if (mainSymptom.Contains("Burn")) return "Burn Specialist";
            if (mainSymptom.Contains("Fever")) return "Infectious Disease Specialist";

            return "General Practitioner";
        }
    }
}